name: Build DiWall

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files
        run: |
          ls -la
          ls -la Sources/DiWall/
      - name: Compile code
        run: |
          swiftc Sources/DiWall/*.swift
